apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: apiserver-proxy-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: "istio"    
spec:
  tls:
    - secretName: {{ .Values.tls.secretName }}
  rules:
  - host: apiserver.{{ .Values.global.domainName }}
    http:
      paths:
      - backend:
          serviceName: apiserver-proxy-service         
          servicePort: {{ .Values.containerPort }}
        path: /.*   
