apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-proxy
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: apiserver-proxy
    spec:
      containers:
      - image: elvido/alpine-nginx-lua:3.6
        name: nginx-proxy
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ .Values.containerPort}}
        volumeMounts:          
          - name: {{ .Values.nginx.configmapName}}
            mountPath: /var/nginx/config          

      - name: dnsmasq
        image: "janeczku/go-dnsmasq:release-1.0.5"
        args:
          - --listen
          - "127.0.0.1:53"
          - --default-resolver
          - --append-search-domains
          - --hostsfile=/etc/hosts
          - --verbose

      volumes:
        - name: {{ .Values.nginx.configmapName}}
          configMap:
            name: {{ .Values.nginx.configmapName}}