apiVersion: v1
kind: Service
metadata:
  annotations:    
  name: apiserver-proxy-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: http
    port: {{.Values.containerPort}}
    protocol: TCP
    targetPort: {{.Values.containerPort}}
  selector:
    app: apiserver-proxy
  
