openapi: '3.0.0'
info:
  version: '1.0.0'
  title: 'Kyma Gateway Metadata API'
tags:
- name: 'service metadata'
  description: 'Service registering API and events catalog.'
paths:
  /v1/metadata/services:
    post:
      tags:
      - 'service metadata'
      summary: 'Registers a new service'
      operationId: 'registerService'
      requestBody:
        description: 'Service object to be registered'
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ServiceDetails'
      responses:
        '200':
          description: 'Successful operation'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceId'
        '400':
          description: 'Bad request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MetadataErrorResponse'
        '500':
          description: 'Internal server error'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MetadataErrorResponse'
    get:
      tags:
      - 'service metadata'
      summary: 'Gets all registered services'
      operationId: 'getServices'
      responses:
        '200':
          description: 'Successful operation'
          content:
            application/json:
              schema:
                type: 'array'
                items:
                  $ref: '#/components/schemas/Service'
        '500':
          description: 'Internal server error'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MetadataErrorResponse'
  /v1/metadata/services/{serviceId}:
    get:
      tags:
      - 'service metadata'
      summary: 'Gets a service by service ID'
      operationId: 'getServiceByServiceId'
      parameters:
      - in: 'path'
        name: 'serviceId'
        description: 'ID of a service'
        required: true
        schema:
          type: 'string'
          format: 'uuid'
      responses:
        '200':
          description: 'Successful operation'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceDetails'
        '404':
          description: 'Service not found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MetadataErrorResponse'
        '500':
          description: 'Internal server error'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MetadataErrorResponse'
    put:
      tags:
      - 'service metadata'
      summary: 'Updates a service by service ID'
      operationId: 'updateService'
      requestBody:
        description: 'Service object to be stored'
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ServiceDetails'
      parameters:
      - in: 'path'
        name: 'serviceId'
        description: 'ID of a service'
        required: true
        schema:
          type: 'string'
          format: 'uuid'
      responses:
        '200':
          description: 'Successful operation'
        '404':
          description: 'Service not found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MetadataErrorResponse'
        '500':
          description: 'Internal server error'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MetadataErrorResponse'
    delete:
      tags:
      - 'service metadata'
      summary: 'Deletes a service by service ID'
      operationId: 'deleteServiceByServiceId'
      parameters:
      - in: 'path'
        name: 'serviceId'
        description: 'ID of a service'
        required: true
        schema:
          type: 'string'
          format: 'uuid'
      responses:
        '204':
          description: 'Successful operation'
        '404':
          description: 'Service not found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MetadataErrorResponse'
        '500':
          description: 'Internal server error'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MetadataErrorResponse'
  /v1/health:
    get:
      summary: 'Returns health of a service'
      operationId: 'getHealth'
      tags:
        - 'health'
      responses:
        '200':
          description: 'The service is in a good health'
  /v1/events:
    post:
      summary: 'Publish an event'
      operationId: 'publishEvent'
      tags:
        - 'publish'
      requestBody:
        description: 'The event to be published'
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PublishRequest'
      responses:
        '200':
          description: 'The event was successfully published'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PublishResponse'
        '400':
          description: 'Bad Request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
        '401':
          description: 'Authentication failure'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
        '403':
          description: 'Not authorized'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
        '500':
          description: 'Server error'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
components:
  schemas:
    ServiceId:
      type: 'object'
      properties:
        id:
          type: 'string'
          format: 'uuid'
    ServiceDetails:
      type: 'object'
      properties:
        provider:
          type: 'string'
        name:
          type: 'string'
        description:
          type: 'string'
        api:
          $ref: '#/components/schemas/Api'
        events:
          $ref: '#/components/schemas/Events'
        documentation:
          $ref: '#/components/schemas/Documentation'
      required:
        - provider
        - name
        - description
    Service:
      type: 'object'
      properties:
        id:
          type: 'string'
          format: 'uuid'
        provider:
          type: 'string'
        name:
          type: 'string'
        description:
          type: 'string'
    Api:
      type: 'object'
      properties:
        targetUrl:
          type: 'string'
          format: 'uri'
        credentials:
          $ref: '#/components/schemas/ApiCredentials'
        spec:
          type: 'object'
          description: 'OpenApi v2 swagger file: https://github.com/OAI/OpenAPI-Specification/blob/master/schemas/v2.0/schema.json'
      required:
        - targetUrl
    Events:
      type: 'object'
      properties:
        spec:
          description: 'AsynApi file v1: https://github.com/asyncapi/asyncapi/blob/develop/schema/asyncapi.json'
          type: 'object'
    Documentation:
      type: 'object'
      properties:
        displayName: 
          type: 'string'
        description: 
          type: 'string'
        type:
          type: 'string'
        tags:
          type: 'array'
          items: 
            type: 'string'
        docs:
          type: 'array'
          items:
            $ref: '#/components/schemas/Document'
      required:
        - displayName
        - description
        - type
    Document:
      type: 'object'
      properties:
        title:
          type: 'string'
        type:
          type: 'string'
        source:
          type: 'string'
      required:
        - title
        - type
        - source
    ApiCredentials:
      type: 'object'
      properties:
        oauth:
          $ref: '#/components/schemas/OAuth'
      required:
        - oauth
    OAuth:
      type: 'object'
      properties:
        url:
          type: 'string'
          format: 'uri'
        clientId:
          type: 'string'
        clientSecret:
          type: 'string'
      required:
        - url
        - clientId
        - clientSecret
    MetadataErrorResponse:
      type: 'object'
      properties:
        code:
          type: 'integer'
        error:
          type: 'string'
    PublishRequest:
      type: object
      description: A Publish request
      properties:
        event-type:
          description: Type of the event.
          type: string
          format: hostname
          pattern: '^[a-zA-Z]+([_\-\.]?[a-zA-Z0-9]+)*$'
          example: 'order.created'
        event-type-version:
          description: The version of the event-type. This is applicable to the data payload alone.
          type: string
          pattern: '^[a-zA-Z0-9]+$'
          example: 'v1'
        event-id:
          description: Optional publisher provided ID (UUID v4) of the to-be-published event. When omitted, one will be automatically generated.
          type: string
          pattern: '^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$'
          example: '31109198-4d69-4ae0-972d-76117f3748c8'
        event-time:
          description: RFC 3339 timestamp of when the event happened.
          type: string
          format: date-time
          example: '2012-11-01T22:08:41+00:00'
        data:
          $ref: '#/components/schemas/AnyValue'
      required:
        - event-type
        - event-type-version
        - event-time
        - data
    PublishResponse:
      type: object
      description: A Publish response
      properties:
        event-id:
          type: string
          description: ID of the published event
          pattern: '^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$'
          example: '31109198-4d69-4ae0-972d-76117f3748c8'
      required:
        - event-id
    AnyValue:
      nullable: false
      description: Can be any value but null.
    APIError:
      type: object
      description: API Error response body
      properties:
        status:
          type: integer
          description: >-
            original HTTP error code, should be consistent with the response HTTP code
          minimum: 100
          maximum: 599
        type:
          type: string
          description: >-
            classification of the error type, lower case with underscore eg
            validation_failure
          pattern: '[a-z]+[a-z_]*[a-z]+'
        message:
          type: string
          description: descriptive error message for debugging
        moreInfo:
          type: string
          format: uri
          description: link to documentation to investigate further and finding support
        details:
          type: array
          description: list of error causes
          items:
            $ref: '#/components/schemas/APIErrorDetail'
      required:
        - status
        - type
    APIErrorDetail:
      description: schema for specific error detail
      type: object
      properties:
        field:
          type: string
          description: >-
            a bean notation expression specifying the element in request
            data causing the error, eg product.variants[3].name, this can
            be empty if violation was not field specific
        type:
          type: string
          description: >-
            classification of the error detail type, lower case with
            underscore eg missing_value, this value must be always
            interpreted in context of the general error type.
          pattern: '[a-z]+[a-z_]*[a-z]+'
        message:
          type: string
          description: descriptive error detail message for debugging
        moreInfo:
          type: string
          format: uri
          description: >-
            link to documentation to investigate further and finding
            support for error detail
      required:
        - type
