{{- if .Values.global.isLocalEnv }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: istio        
  name: core-jaeger
  namespace: kyma-system  
spec:
  tls:
    - secretName: {{.Values.global.istio.tls.secretName }}
  rules:
  - host: jaeger.{{ .Values.global.domainName }}
    http:
      paths:
      - backend:
          serviceName: core-jaeger
          servicePort: {{ .Values.service.uiPort }}
        path: /.*    
{{- end }}
