apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "minio.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: "istio"        
  labels:
    app: {{ template "minio.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"  
spec:
  tls:
    - secretName: {{.Values.global.istio.tls.secretName }}
  rules:
  - host: minio.{{ .Values.global.domainName }}
    http:
      paths:
      - path: /.*
        backend:
          serviceName: {{ template "minio.fullname" . }}
          servicePort: 9000