---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dex-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: "istio"          
  labels:
    app: dex
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}  
spec:
  tls:
    - secretName: {{.Values.global.istio.tls.secretName }}
  rules:
  - host: dex.{{ .Values.global.domainName }}
    http:
      paths:
      - backend:
          serviceName: dex-service
          servicePort: {{ .Values.containerPort }}
        path: /.*
