---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: configurations-generator
  labels:
    app: configurations-generator
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: configurations-generator
        chart: {{ .Chart.Name }}-{{ .Chart.Version }}
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - image: {{ .Values.global.containerRegistry.path }}/{{ .Chart.Name }}:{{ .Chart.Version }}
        name: configurations-generator
        command: [
          "/app",
          "-kube-config-custer-name={{ .Values.kubeConfig.clusterName }}",
          "-kube-config-url={{ .Values.kubeConfig.url }}",
          "-kube-config-ca={{ .Values.kubeConfig.ca }}"
        ]
        ports:
          - name: http
            containerPort: 8000
