---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: configurations-generator
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: "istio"          
  labels:
    app: configurations-generator
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  tls:
    - secretName: {{.Values.global.istio.tls.secretName }}
  rules:
  - host: configurations-generator.{{ .Values.global.domainName }}
    http:
      paths:
      - backend:
          serviceName: configurations-generator
          servicePort: 8000
        path: /.*
