# Example of JWT authentication rule securing /weather enpoint in sample service
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: configurations-generator-jwt
  # namespace must be settled in istio-system
  namespace: istio-system
  labels:
    app: configurations-generator
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  # more information about vocabulary available for match condition can be found in istio docu (https://istio.io/docs/reference/config/mixer/attribute-vocabulary.html)
  match: ( destination.service == "configurations-generator.{{ .Release.Namespace }}.svc.cluster.local" )
  actions:
  # handler and instances must not be changed
  - handler: handler.jwt
    instances:
    - jwt.auth.istio-system