---
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: configurations-generator-cors
  labels:
    app: configurations-generator
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  destination:
    name: configurations-generator
  corsPolicy:
    allowOrigin:
      - "*"
    allowMethods:
      - GET
      - OPTIONS
    allowHeaders:
      - "authorization"