---
apiVersion: v1
kind: Service
metadata:
  name: configurations-generator
  labels:
    app: configurations-generator
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  type: NodePort
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  selector:
    app: configurations-generator
