apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ template "stability-checker.name" . }}

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "stability-checker.name" . }}

subjects:
- kind: ServiceAccount
  name: {{ template "stability-checker.name" . }}
  namespace: {{ .Release.Namespace}}
