apiVersion: v1
data:
  "tls.crt": {{ .Values.global.tlsCrt}}
  "tls.key": {{ .Values.global.tlsKey }}
kind: Secret
metadata:
  name: istio-ingress-certs
  namespace: istio-system
type: kubernetes.io/tls
