apiVersion: v1
kind: Service
metadata:
  name: istio-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    istio: ingress
spec:
{{- if .Values.service.externalPublicIp }}
  loadBalancerIP: "{{ .Values.service.externalPublicIp }}"
{{- end }}
  type: {{ .Values.service.type }}
  selector:
    istio: ingress
  ports:
    {{- range $key, $val := .Values.service.ports }}
    -
      {{- range $pkey, $pval := $val }}
      {{ $pkey}}: {{ $pval }}
      {{- end }}
    {{- end }}  
---
