# Default values for service-instances-ui.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  name: ui-api-layer
  pullPolicy: IfNotPresent
service:
  internalPort: 3000
  externalPort: 3000
  protocol: TCP
ingress:
  enabled: true
  host: ui-api
  annotations:
    kubernetes.io/ingress.class: "istio"
auth:
  jwt:
    name: graphql-api-jwt-rule
