apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: {{ .Values.auth.jwt.name }}
  namespace: istio-system  
spec:    
  match:  (destination.service == "{{ template "fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local") && (request.path == "/graphql" || request.path.startsWith("/graphql?")) && (request.method == "POST")
  actions:
  - handler: handler.jwt
    instances:
    - jwt.auth.istio-system